version: '3.8'

volumes:
  db_storage:
  n8n_storage:
  redis_storage:

networks:
  n8n_network:
    name: n8n_network

x-shared: &shared
  restart: always
  # Use the custom image instead of the official one
  image: christiankuri/n8n-with-ffmpeg-and-curl
  networks:
    - n8n_network
  environment:
    - N8N_HOST=${HOST}
    - WEBHOOK_URL=https://${HOST}/
    - N8N_PROTOCOL=https
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
    - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    - EXECUTIONS_MODE=regular
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true
    - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}
    - N8N_RELEASE_DATE=${N8N_RELEASE_DATE}
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}
    - N8N_PAYLOAD_SIZE_MAX=512
    - NODE_OPTIONS=--max-old-space-size=4096
    - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    - N8N_FILESYSTEM_MAX_SIZE=512
  volumes:
    - n8n_storage:/home/node/.n8n
  # Remove the custom entrypoint since ffmpeg and curl are already installed in the image
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16
    restart: always
    networks:
      - n8n_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    volumes:
      - db_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:6-alpine
    restart: always
    networks:
      - n8n_network
    volumes:
      - redis_storage:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *shared
    container_name: n8n
    ports:
      - 5678:5678
    # Forward to: n8n:5678
